/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cusmanagment;

import DBConnection.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static javax.swing.DropMode.INSERT;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Charuni
 */
public class AddShops extends javax.swing.JFrame {
    
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;  
    /**
     * Creates new form AddShops
     */
    public AddShops() {
        initComponents();
        
        con = DBConnection.connect();
        ShopIDbox.setEditable(false);
        tableload();
        id_auto();
    }
    
    public void id_auto(){
        
            String sql = "SELECT MAX(RIGHT(shopID, 4)) AS no FROM shops";
            try {
                pst = con.prepareStatement(sql);
            
            rs = pst.executeQuery();
            
            while(rs.next()){
                if(rs.first() == false){
                    ShopIDbox.setText("L0001");
                }
                else{
                    rs.last();
                    int set_id = rs.getInt(1) + 1;
                    String no = String.valueOf(set_id);
                    
                    int id_next = no.length();
                    
                    for(int a = 0 ; a < 4 - id_next ; a++){
                        no = "0" + no;
                    }
                    
                    ShopIDbox.setText("L" + no);
                }
            }
            }catch (SQLException ex) {
                Logger.getLogger(AddShops.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
    
   public void tableload()
  {
      try{
       String sql = "SELECT ShopID,ShopName,OwnerName,RouteID,TelephoneNo FROM shops  ";
       pst=con.prepareStatement(sql);
       rs=pst.executeQuery();
       jTable1.setModel(DbUtils.resultSetToTableModel(rs));
   }catch(Exception e){
   }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ShopIDbox = new javax.swing.JTextField();
        ShopNamebox = new javax.swing.JTextField();
        OwnerNamebox = new javax.swing.JTextField();
        RouteIDbox = new javax.swing.JTextField();
        TelephoneNobox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jToolBar3.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar3.setRollover(true);
        jToolBar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_blue.png"))); // NOI18N
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setFocusable(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setOpaque(false);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cusmanagment/photos/rrrr.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ShopID", "ShopName", "OwnerName", "RouteID", "TelephoneNo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cusmanagment/photos/FormatFactory17009648-shop-ilustración~1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Shops Detials");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Shop ID");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Shop Name");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Owner Name");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Route ID");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telephone No");

        ShopIDbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopIDboxActionPerformed(evt);
            }
        });

        ShopNamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShopNameboxActionPerformed(evt);
            }
        });

        OwnerNamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnerNameboxActionPerformed(evt);
            }
        });

        RouteIDbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouteIDboxActionPerformed(evt);
            }
        });

        TelephoneNobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneNoboxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Shop Name");

        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RouteIDbox, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(TelephoneNobox)
                                    .addComponent(ShopNamebox, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(ShopIDbox)
                                    .addComponent(OwnerNamebox)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ShopNamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OwnerNamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RouteIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelephoneNobox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ShopIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShopIDboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopIDboxActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_ShopIDboxActionPerformed

    private void ShopNameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShopNameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShopNameboxActionPerformed

    private void OwnerNameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnerNameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OwnerNameboxActionPerformed

    private void RouteIDboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouteIDboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RouteIDboxActionPerformed

    private void TelephoneNoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneNoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneNoboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int y = JOptionPane.showConfirmDialog(null, "Do you really want to update");
    
    String errorMessage = "Error\n";
    
    if(y==0)
    {
        int x=0;
        
        if(ShopIDbox.getText().isEmpty())
        {
            x=1;
            errorMessage = errorMessage.concat("Shop ID can't be empty\n");
        }else
        {   System.out.println(ShopIDbox.getText());
            Pattern p = Pattern.compile("(L)([0-9]+){4}");
            System.out.println("2");
            Matcher m = p.matcher(ShopIDbox.getText());
            
            if(m.find() && m.group().equals(ShopIDbox.getText())){
                System.out.println("match");
             }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter a valid Shop ID. \n");
            }
        }
        if(ShopNamebox.getText().isEmpty())
        {
            System.out.println("Inside1");
            x = 1;
            errorMessage = errorMessage.concat("Shop Name can't be empty\n");
        }
        else{
//            if(ShopNamebox.matches("[a-zA-Z1-9]",ShopNamebox.getText())== false){
//                x = 1;
//                errorMessage = errorMessage.concat("Enter Only Letters for shop name.\n");
//            }

               Pattern p = Pattern.compile("[a-zA-Z]+");
         
               
                
                System.out.println("else Inside");
                Matcher m = p.matcher(ShopNamebox.getText());
            
             if(m.find() && m.group().equals(ShopNamebox.getText())){
                System.out.println("match");
            }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter only letters for shop name.\n");
            }
        }   
            
        if(OwnerNamebox.getText().isEmpty()){
            x = 1;
            System.out.println("Inside2");
            errorMessage = errorMessage.concat("Owner name can't be empty.\n");
        }else{
               // if(Pattern.matches("[a-zA-Z]*",OwnerNamebox.getText())== false){
                Pattern p = Pattern.compile("[a-zA-Z]+");
         
                System.out.println("else Inside");
                Matcher m = p.matcher(OwnerNamebox.getText());
            
             if(m.find() && m.group().equals(OwnerNamebox.getText())){
                System.out.println("match");
            }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter only letters for owner name.\n");
            }
        }
         if(RouteIDbox.getText().isEmpty()){
            x = 1;
            System.out.println("Inside3");
            errorMessage = errorMessage.concat("RouterID can't be empty.\n");
        
         }else{
            Pattern p = Pattern.compile("(R)([0-9]+){4}");
         
            System.out.println("2");
            Matcher m = p.matcher(RouteIDbox.getText());
            
            if(m.find() && m.group().equals(RouteIDbox.getText())){
                System.out.println("match");
            }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter a valid route ID.\n");
            }
         }
        
        if(TelephoneNobox.getText().isEmpty())
        {
            x=1;
            errorMessage = errorMessage.concat("Telephone Number can't be empty\n");
        }else{
            System.out.println(TelephoneNobox.getText());
            Pattern p = Pattern.compile("([0-9]+){10}");
            Matcher m = p.matcher(TelephoneNobox.getText());
            
            if(m.find() && m.group().equals(TelephoneNobox.getText())){
            }
            else{
                x = 1;
                errorMessage = errorMessage.concat("Telephone Number should contain 10 numbers.\n");
            }
            }

        
           
        if(x == 0){
        System.out.println("Yes");
        String ShopID = ShopIDbox.getText();
        String ShopName = ShopNamebox.getText();
        String OwnerName = OwnerNamebox.getText();
        String RouteID = RouteIDbox.getText();
        String TelephoneNo = TelephoneNobox.getText();
        
        String sql = "Update shops SET ShopID = '" +ShopID+"',ShopName='"+ShopName+"',OwnerName='"+OwnerName+"',RouteID='"+RouteID+"',TelephoneNo='"+TelephoneNo+"' WHERE ShopID='" +ShopID+"'";
        try{
        pst = con.prepareStatement(sql);
        pst.execute();
        id_auto();
        
        JOptionPane.showMessageDialog(null, "Updated successfully!!");
        
        tableload();
        }catch(Exception e){
              System.err.println(e);  
        }            
        ShopIDbox.setText(null);
        ShopNamebox.setText(null);
        OwnerNamebox.setText(null);
        RouteIDbox.setText(null);
        TelephoneNobox.setText(null);
        }else{
            JOptionPane.showMessageDialog(null,errorMessage);
            tableload();
            
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to Delete This");
        
        if(x==0)
        {
            String ShopID = ShopIDbox.getText();
            //String ShopID;
            String sql = "DELETE from shops where ShopID = '"+ ShopID +"'";
            try{
                pst = con.prepareStatement(sql);
                pst.execute();
                tableload();
                id_auto();
                
            JOptionPane.showConfirmDialog(null, "successfully!!");
        
            }catch (Exception e){
                System.err.println(e);
            }
        }



// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

                    // TODO add your handling code here: 
            String ShopID = ShopIDbox.getText();
            String ShopName = ShopNamebox.getText();
            String OwnerName = OwnerNamebox.getText();
            String RouteID = RouteIDbox.getText();
            String TelephoneNo = TelephoneNobox.getText();
                    String errorMessage = "Error...\n";
                    
           JOptionPane.showMessageDialog(null, "Updated successfully!!");          
        
        
        
        String Type = "customer";
        
        int x=0;
        
        if(ShopIDbox.getText().isEmpty())
        {
            x=1;
            errorMessage = errorMessage.concat("Shop ID can't be empty\n");
        }else
        {   System.out.println(ShopIDbox.getText());
            Pattern p = Pattern.compile("(L)([0-9]+){4}");
            System.out.println("2");
            Matcher m = p.matcher(ShopIDbox.getText());
            
            if(m.find() && m.group().equals(ShopIDbox.getText())){
                System.out.println("match");
             }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter a valid Shop ID. \n");
            }
        }
        if(ShopNamebox.getText().isEmpty())
        {
            System.out.println("Inside1");
            x = 1;
            errorMessage = errorMessage.concat("Shop Name can't be empty\n");
        }
        else{
//            if(ShopNamebox.matches("[a-zA-Z1-9]",ShopNamebox.getText())== false){
//                x = 1;
//                errorMessage = errorMessage.concat("Enter Only Letters for shop name.\n");
//            }

               Pattern p = Pattern.compile("[a-zA-Z]+");
         
               
                
                System.out.println("else Inside");
                Matcher m = p.matcher(ShopNamebox.getText());
            
             if(m.find() && m.group().equals(ShopNamebox.getText())){
                System.out.println("match");
            }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter only letters for shop name.\n");
            }
        }   
            
        if(OwnerNamebox.getText().isEmpty()){
            x = 1;
            System.out.println("Inside2");
            errorMessage = errorMessage.concat("Owner name can't be empty.\n");
        }else{
               // if(Pattern.matches("[a-zA-Z]*",OwnerNamebox.getText())== false){
                Pattern p = Pattern.compile("[a-zA-Z]+");
         
                System.out.println("else Inside");
                Matcher m = p.matcher(OwnerNamebox.getText());
            
             if(m.find() && m.group().equals(OwnerNamebox.getText())){
                System.out.println("match");
            }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter only letters for owner name.\n");
            }
        }
         if(RouteIDbox.getText().isEmpty()){
            x = 1;
            System.out.println("Inside3");
            errorMessage = errorMessage.concat("RouterID can't be empty.\n");
        
         }else{
            Pattern p = Pattern.compile("(R)([0-9]+){4}");
         
            System.out.println("2");
            Matcher m = p.matcher(RouteIDbox.getText());
            
            if(m.find() && m.group().equals(RouteIDbox.getText())){
                System.out.println("match");
            }else{
                System.out.println("do not match");
                x=1;
                errorMessage = errorMessage.concat("Enter a valid route ID.\n");
            }
         }
        
        if(TelephoneNobox.getText().isEmpty())
        {
            x=1;
            errorMessage = errorMessage.concat("Telephone Number can't be empty\n");
        }else{
            System.out.println(TelephoneNobox.getText());
            Pattern p = Pattern.compile("([0-9]+){10}");
            Matcher m = p.matcher(TelephoneNobox.getText());
            
            if(m.find() && m.group().equals(TelephoneNobox.getText())){
            }
            else{
                x = 1;
                errorMessage = errorMessage.concat("Telephone Number should contain 10 numbers.\n");
            }
            }

        
           
        if(x == 0){
            try {
              
            String q = "INSERT INTO shops (ShopID,ShopName,OwnerName,RouteID,TelephoneNo) VALUES ('" +ShopID+"','"+ShopName+"','"+OwnerName+"','"+RouteID+"','"+TelephoneNo+"')";
            
            pst = con.prepareStatement(q);
           
            pst.execute();
            
            tableload();
            id_auto();
          
            } catch (Exception e) {
                System.out.println(e);
            }
        }else{
        
        JOptionPane.showMessageDialog(null,errorMessage);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    int r = jTable1.getSelectedRow();
    
    String ShopID = jTable1.getValueAt(r, 0).toString();
    String ShopName = jTable1.getValueAt(r, 1).toString();
    String OwnerName = jTable1.getValueAt(r, 2).toString();
    String  RouteID  = jTable1.getValueAt(r, 3).toString();
    String TelephoneNo = jTable1.getValueAt(r, 4).toString();
    
    ShopIDbox.setText(ShopID);
    ShopNamebox.setText(ShopName);
    OwnerNamebox.setText(OwnerName);
    RouteIDbox.setText(RouteID);
    TelephoneNobox.setText(TelephoneNo);
    
    
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = jTextField1.getText();
        String sql = "Select ShopID,ShopName,OwnerName,RouteID,TelephoneNo from shops where ShopName LIKE  '%"+name+"%'";
        try{
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        }catch(Exception e){
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            ShopIDbox.setText(null);
            ShopNamebox.setText(null);
            OwnerNamebox.setText(null);
            RouteIDbox.setText(null);
            TelephoneNobox.setText(null);
            id_auto();
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        CustomerManagementHome mh=new CustomerManagementHome();
        mh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton18ActionPerformed
        
    /**
     * @param args the command line arguments
     */
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddShops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddShops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddShops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddShops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddShops().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OwnerNamebox;
    private javax.swing.JTextField RouteIDbox;
    private javax.swing.JTextField ShopIDbox;
    private javax.swing.JTextField ShopNamebox;
    private javax.swing.JTextField TelephoneNobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}