/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import project_distributers.DBConnection;

/**
 *
 * @author Nilfa.RS
 */
public class EmpRegi extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    
    
    
    public EmpRegi() {
        initComponents();
        
        //connection to the DB
        con=DBConnection.connect();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        emptype = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        appdate = new com.toedter.calendar.JDateChooser();
        nic1 = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        uname1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Registration");
        setMinimumSize(new java.awt.Dimension(1372, 771));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Appointment Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(660, 580, 190, 23);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date of Birth");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 480, 190, 23);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIC Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 180, 190, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 330, 190, 23);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 130, 200, 23);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 430, 190, 23);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee Type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(660, 530, 190, 20);

        email.setBackground(new java.awt.Color(204, 204, 255));
        email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(email);
        email.setBounds(1000, 420, 230, 40);

        name.setBackground(new java.awt.Color(204, 204, 255));
        name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(1000, 120, 230, 40);

        gender.setBackground(new java.awt.Color(204, 204, 255));
        gender.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        gender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gender.setMinimumSize(new java.awt.Dimension(1370, 770));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender);
        gender.setBounds(1000, 220, 230, 40);

        password.setBackground(new java.awt.Color(204, 204, 255));
        password.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(1000, 370, 230, 40);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savelll.png"))); // NOI18N
        jButton1.setText("SAVE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1000, 650, 100, 50);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h.png"))); // NOI18N
        jButton2.setText("RESET");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1130, 650, 100, 50);

        emptype.setBackground(new java.awt.Color(204, 204, 255));
        emptype.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        emptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Employee Type", "Administrator", "Accountant", "Sales Representative", "Promotion Manager", "Transport Manager", "Sales Manager", " ", " " }));
        emptype.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(emptype);
        emptype.setBounds(1000, 520, 230, 40);

        jToolBar1.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton14.setBackground(new java.awt.Color(51, 0, 0));
        jButton14.setForeground(new java.awt.Color(51, 0, 51));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_blue.png"))); // NOI18N
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setOpaque(false);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton16);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 270, 530, 70);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("                                           Employee Registration");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(660, 20, 600, 30);

        dob.setBackground(new java.awt.Color(204, 204, 255));
        dob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dob.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dob);
        dob.setBounds(1000, 470, 230, 40);

        appdate.setBackground(new java.awt.Color(204, 204, 255));
        appdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        appdate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(appdate);
        appdate.setBounds(1000, 570, 230, 40);

        nic1.setBackground(new java.awt.Color(204, 204, 255));
        nic1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        nic1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(nic1);
        nic1.setBounds(1000, 170, 230, 40);

        mob.setBackground(new java.awt.Color(204, 204, 255));
        mob.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        mob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(mob);
        mob.setBounds(1000, 270, 230, 40);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mobile");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(660, 280, 190, 23);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(660, 230, 190, 23);

        uname1.setBackground(new java.awt.Color(204, 204, 255));
        uname1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        uname1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(uname1);
        uname1.setBounds(1000, 320, 230, 40);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(660, 380, 190, 23);

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setText("DemoValid Entries");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 650, 160, 50);

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton5.setText("DemoInvalid Entries");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setPreferredSize(new java.awt.Dimension(131, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(830, 650, 150, 50);

        jLabel10.setBackground(new java.awt.Color(0, 0, 102));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(620, 30, 680, 680);

        jLabel12.setBackground(new java.awt.Color(0, 0, 102));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("B I S C U I T  M A N U F A C T U R E R S");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(140, 100, 270, 40);

        jLabel21.setBackground(new java.awt.Color(0, 0, 102));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("           L U C K Y L A N D");
        jLabel21.setOpaque(true);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(90, 40, 300, 60);

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 20, 510, 160);

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-40, -6, 570, 860);

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1580, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        String vemail=email.getText();
        String vmob=mob.getText();
        String vuname=uname1.getText();
        String vname=name.getText();
        String vnic=nic1.getText();
        String vgender=gender.getSelectedItem().toString();
        
        String vpassword=password.getText();
        String vemptype=emptype.getSelectedItem().toString();

       

       //Strating Validations.....
       
        String emailPat="^[a-zA-Z0-9]{1,20}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";   
        Pattern pat=Pattern.compile(emailPat);
        Matcher regexMatcher=pat.matcher(vemail);
       
         String nic="^[0-9]{9}[Vv]$";
         Pattern pat1=Pattern.compile(nic);
         Matcher regexMatcher1=pat1.matcher(vnic);
         
         String unamepat="^[a-zA-Z0-9]{1,30}$";
         Pattern pat2=Pattern.compile(unamepat);
         Matcher regexMatcher2=pat2.matcher(vuname);
         
         
         
         String passpat="((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20})";
         Pattern pat3=Pattern.compile(passpat);
         Matcher regexMatcher3=pat3.matcher(password.getText());
         
         String mobpat="^[0-9]{10}$";
         Pattern pat4=Pattern.compile(mobpat);
         Matcher regexMatcher4=pat4.matcher(vmob);
                 
        Date vdc=(Date)appdate.getDate();
        Date vdc1=(Date)dob.getDate();


         
         if((vname.trim().isEmpty() )||( vemail.trim().isEmpty() )||( vmob.trim().isEmpty() ) ||(vuname.trim().isEmpty() )||(vnic.trim().isEmpty() )||(vgender.trim().isEmpty() )||(vemptype.trim().isEmpty() )||(vpassword.trim().isEmpty() )){
  
         
                     JOptionPane.showMessageDialog(null,"Text Fields can not be empty!");    

         }
         
        
        else if (vdc == null) 
                 
             {
              JOptionPane.showMessageDialog(this, "Date can not be empty!");
                             
             }
       
       
       
       
         else if (vdc1 == null) 
                 
             {
              JOptionPane.showMessageDialog(this, "Date can not be empty!");
                             
             }
       
         
         
        else if(!regexMatcher.matches()){
        
        JOptionPane.showMessageDialog(null,"Invalid E-mail Format!");
            
            
        }
         
         else if(!regexMatcher2.matches()){
         
        JOptionPane.showMessageDialog(null,"Invalid Username Format!");

         
         }
         
         else if(!regexMatcher4.matches())
         {
           JOptionPane.showMessageDialog(null,"Invalid Mobile Number Format.There shoould be 10 digits.No Strings!");

         
         }
         
         
         else if(!regexMatcher1.matches()){
         
              JOptionPane.showMessageDialog(null,"Invalid NIC Format.There shpuld be 9 digits and last character should be 'V' OR 'v' !");

         }
         
         else if(!regexMatcher3.matches()){
    
             JOptionPane.showMessageDialog(null,"Invalid Password Format.Include atleast 6 charactors with Upper case,Special charactor and a Number! ");

    
            }
         
         
         else {
             
             
        try{
          
        
        
          
        SimpleDateFormat oDateFormat=new SimpleDateFormat("yyyy-MM-dd");
        String vd=oDateFormat.format(vdc);
            
        SimpleDateFormat oDateFormat1=new SimpleDateFormat("yyyy-MM-dd");
        String vd1=oDateFormat1.format(vdc1);   
            
        String q="INSERT INTO employee (empName,NIC,gender,mobile,uname,password,email,dob,emptype,appDate) values ('"+vname+"','"+vnic+"','"+vgender+"','"+vmob+"','"+vuname+"','"+vpassword+"','"+vemail+"','"+vd1+"','"+vemptype+"','"+vd+"')";
        pst=con.prepareStatement(q);
        pst.execute();
        AlertBox.infoBox("Employee Inserted Successfully", "Successful");
        
        name.setText("");
        email.setText("");
        gender.setSelectedItem("Select Gender");
        password.setText("");
         //dob.setText("");
        emptype.setSelectedItem("Select Employee Type");
        //appdate.setText("");
        mob.setText("");
        uname1.setText("");
        nic1.setText("");
        dob.setCalendar(null);
        appdate.setCalendar(null);
        
        }
        
        catch (Exception e){
        
            
              AlertBox.infoBox("Something went wrong! Please check the Data", "Error");
        
              name.setText("");
              email.setText("");
              gender.setSelectedItem("Select Gender");
              password.setText("");
              emptype.setSelectedItem("Select Employee Type");
              mob.setText("");
              uname1.setText("");
              nic1.setText("");
              dob.setCalendar(null);
              appdate.setCalendar(null);
             
        //System.out.println(e);
       }
       
        }
         
         
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        name.setText("");
        email.setText("");
        gender.setSelectedItem("Select Gender");
        password.setText("");
        //dob.setText("");
        emptype.setSelectedItem("Select Employee Type");
        //appdate.setText("");
        mob.setText("");
        uname1.setText("");
        nic1.setText("");
        dob.setCalendar(null);
        appdate.setCalendar(null);     

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        MainHomeUI mh=new MainHomeUI();
        mh.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton16ActionPerformed

    
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
    }//GEN-LAST:event_passwordActionPerformed

    
    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        AdminmenuUI mh=new AdminmenuUI();
        mh.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton14ActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased

             }//GEN-LAST:event_nameKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        name.setText("Oliver");
        email.setText("oliver@ymail.com");
        gender.setSelectedItem("Male");
        password.setText("Oliver@123");
        //dob.setText("");
        emptype.setSelectedItem("Administrator");
        //appdate.setText("");
        mob.setText("0771756342");
        uname1.setText("oliver123");
        nic1.setText("903457564V");
       // dob.setCalendar(null);
      //  appdate.setCalendar(null);  
        
          
   String date = "2016-12-31";
   java.util.Date date2 = null;
        try {
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(EmpRegi.class.getName()).log(Level.SEVERE, null, ex);
        }
         appdate.setDate(date2);
         
         
        
         String dobdate = "1985-12-31";
   java.util.Date dobdate2 = null;
        try {
            dobdate2 = new SimpleDateFormat("yyyy-MM-dd").parse(dobdate);
        } catch (ParseException ex) {
            Logger.getLogger(EmpRegi.class.getName()).log(Level.SEVERE, null, ex);
        }
         dob.setDate(dobdate2);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling   
        name.setText("123");
        
        email.setText("loral@kl");
        gender.setSelectedItem("Female");
        password.setText("apple");
        //dob.setText("");
        emptype.setSelectedItem("Sales Manager");
        //appdate.setText("");
        mob.setText("0776");
        uname1.setText("ema123");
        nic1.setText("973678231");
        
  
          String date = "2014-04-28";
   java.util.Date date2 = null;
        try {
            date2 = new SimpleDateFormat("yyyy-MM-dd").parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(EmpRegi.class.getName()).log(Level.SEVERE, null, ex);
        }
         appdate.setDate(date2);
         
         
        
         String dobdate = "1995-10-25";
   java.util.Date dobdate2 = null;
        try {
            dobdate2 = new SimpleDateFormat("yyyy-MM-dd").parse(dobdate);
        } catch (ParseException ex) {
            Logger.getLogger(EmpRegi.class.getName()).log(Level.SEVERE, null, ex);
        }
         dob.setDate(dobdate2);
             
    }//GEN-LAST:event_jButton5ActionPerformed

 
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpRegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpRegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpRegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpRegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpRegi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser appdate;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> emptype;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField mob;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField uname1;
    // End of variables declaration//GEN-END:variables
}
