/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import project_distributers.DBConnection;

/**
 *
 * @author Nilfa.RS
 */
public class viewLeave extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    
    /**
     * Creates new form viewLeave
     */
    public viewLeave() {
        initComponents();
        con=DBConnection.connect();
        update_table();
        
        
    }

    private void update_table(){
    
        try{
            String sql="select*from empleave";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery(sql);
            leave_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
         
        JOptionPane.showMessageDialog(null,e);
        
        }
    
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        ndays = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        leaveid = new javax.swing.JLabel();
        dc = new com.toedter.calendar.JDateChooser();
        reason = new javax.swing.JComboBox<>();
        empid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leave_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leave Records");
        setMinimumSize(new java.awt.Dimension(1380, 775));
        setResizable(false);
        getContentPane().setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton14.setBackground(new java.awt.Color(51, 0, 0));
        jButton14.setForeground(new java.awt.Color(51, 0, 51));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_blue.png"))); // NOI18N
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setOpaque(false);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton16);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(10, 190, 480, 70);

        ndays.setBackground(new java.awt.Color(204, 204, 255));
        ndays.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ndays.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ndays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndaysActionPerformed(evt);
            }
        });
        getContentPane().add(ndays);
        ndays.setBounds(260, 490, 220, 40);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 430, 150, 23);

        jLabel21.setBackground(new java.awt.Color(0, 0, 102));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("           L U C K Y L A N D");
        jLabel21.setOpaque(true);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(60, 40, 300, 60);

        jLabel12.setBackground(new java.awt.Color(0, 0, 102));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("B I S C U I T  M A N U F A C T U R E R S");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 100, 270, 40);

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 20, 480, 160);

        delete.setBackground(new java.awt.Color(153, 153, 153));
        delete.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        delete.setText("DELETE");
        delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(380, 640, 100, 50);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Leave ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 310, 160, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reason");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 560, 110, 23);

        update.setBackground(new java.awt.Color(153, 153, 153));
        update.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h.png"))); // NOI18N
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(260, 640, 100, 50);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("No of Days");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 500, 120, 23);

        leaveid.setBackground(new java.awt.Color(204, 204, 255));
        leaveid.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        leaveid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaveid.setOpaque(true);
        getContentPane().add(leaveid);
        leaveid.setBounds(260, 310, 220, 40);

        dc.setBackground(new java.awt.Color(204, 204, 255));
        dc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dc.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dc);
        dc.setBounds(260, 420, 220, 40);

        reason.setBackground(new java.awt.Color(153, 255, 255));
        reason.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        reason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Reason", "Sick", "Funeral", "Accident" }));
        reason.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(reason);
        reason.setBounds(260, 560, 220, 40);

        empid.setBackground(new java.awt.Color(204, 204, 255));
        empid.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        empid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        empid.setOpaque(true);
        getContentPane().add(empid);
        empid.setBounds(260, 360, 220, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Employee ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 360, 160, 30);

        jButton2.setBackground(new java.awt.Color(255, 51, 255));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.png"))); // NOI18N
        jButton2.setText("Generate Report");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 630, 390, 40);

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 290, 480, 430);

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 500, 790);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("                  View Leave Applications");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(770, 20, 390, 30);

        leave_table.setBackground(new java.awt.Color(204, 255, 204));
        leave_table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leave_table.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        leave_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        leave_table.setSelectionBackground(new java.awt.Color(0, 0, 102));
        leave_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leave_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(leave_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(520, 100, 830, 470);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 40, 850, 680);

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 1440, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        LeaveApplication la=new LeaveApplication();
        la.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        MainHomeUI mh=new MainHomeUI();
        mh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void ndaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndaysActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

            String val1=leaveid.getText();
            
            if(val1.isEmpty()){
                        JOptionPane.showMessageDialog(null,"Employee ID should be Numeric It can not be Empty!");

            }
            else{
        
        int p=JOptionPane.showConfirmDialog(null,"Do you really want to Delete the Data?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){

            String sql="delete from empleave where leaveID=?";

            try{

                pst=con.prepareStatement(sql);
                pst.setString(1,leaveid.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Record Deleted Successfully!");

            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);

            }

            update_table();
    }//GEN-LAST:event_deleteActionPerformed
   }
  }
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        String val1=leaveid.getText();
        String val3=ndays.getText();
        String val4=reason.getSelectedItem().toString();

         
             
        
        //Strating Validations.....

        String ndayspat="^[0-9]{1,31}$";
        Pattern pat2=Pattern.compile(ndayspat);
        Matcher regexMatcher2=pat2.matcher(val3);

        Date vdc=(Date)dc.getDate();

        
        
            if(val1.isEmpty())
            {
                        JOptionPane.showMessageDialog(null,"Employee ID should be Numeric It can not be Empty!");

            }
     
           
       
            else if(!regexMatcher2.matches())
            {

            JOptionPane.showMessageDialog(null,"No of Days should be Numeric!");

           }
            
            else if(vdc==null){
            
                        JOptionPane.showMessageDialog(null,"Date cannot be Empty!");

            
            
            }
        

            else {

            try
            {
             SimpleDateFormat oDateFormat=new SimpleDateFormat("yyyy-MM-dd");
             String val5=oDateFormat.format(vdc);

                String sql="update empleave set noDays='"+val3+"',reason='"+val4+"',date='"+val5+"' where empid='"+val1+"'";
                pst=con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Record Updated Successfully!");

            }

            catch(Exception e)
            {

                JOptionPane.showMessageDialog(null,e);

            }

            update_table();
    }//GEN-LAST:event_updateActionPerformed
   
  }
    
    private void leave_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leave_tableMouseClicked

        try{
            
            
            int row=leave_table.getSelectedRow();
            
            String Table_click=(leave_table.getModel().getValueAt(row, 0).toString());

            String sql="select*from empleave where leaveID='"+Table_click+"'";

            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){

                String add1=rs.getString("empid");
                empid.setText(add1);
                
                String add2=rs.getString("leaveID");
                leaveid.setText(add2);
                
                String add3=rs.getString("noDays");
                ndays.setText(add3);
                
                String add4=rs.getString("reason");
                reason.setSelectedItem(add4);
                
                String dateValue = rs.getString("date"); // What ever column
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);

                dc.setDate(date);
            }
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_leave_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //        try
        //        {
            //        String report="C:\\Users\\Nilfa.RS\\JaspersoftWorkspace\\MyReports\\ReportEmployeeInfo.jrxml";
            //        JasperReport jr=JasperCompileManager.compileReport(report);
            //        JasperPrint jp=JasperFillManager.fillReport(jr,null,con);
            //        JasperViewer.viewReport(jp);
            //
            //
            //
            //        }
        //
        //        catch(Exception e)
        //        {
            //
            //               JOptionPane.showMessageDialog(null,e);
            //
            //
            //        }

         
              try {
            DBConnection db = new DBConnection();
            Connection con = db.connect();
            
            InputStream in = new FileInputStream(new File("C:\\Users\\Nilfa.RS\\Desktop\\TEchNinjas_project\\TEchNinjas_project\\Project_distributers\\Project_distributers\\src\\jasper\\ReportLeaveInfo.jrxml"));
            JasperDesign jd = JRXmlLoader.load(in);
            String sql = "select * from empleave";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            HashMap para = new HashMap();
            JasperPrint j = JasperFillManager.fillReport(jr, para,con);
            JasperViewer.viewReport(j,false);
            //OutputStream os = new FileOutputStream(new File("E:\\Report"));
            //JasperExportManager.exportReportToPdfStream(j,os);
        } catch (Exception e) {
        
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLeave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dc;
    private javax.swing.JButton delete;
    private javax.swing.JLabel empid;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable leave_table;
    private javax.swing.JLabel leaveid;
    private javax.swing.JTextField ndays;
    private javax.swing.JComboBox<String> reason;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
