/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.BasicConfigurator;
import project_distributers.DBConnection;



/**
 *
 * @author Nilfa.RS
 */
public class viewEmployee extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    /**
     * Creates new form viewEmployee
     */
    public viewEmployee() {
        initComponents();
         con=DBConnection.connect();
         update_table();
                       
                        
                        
    }

    private void update_table(){
    
        try{
            String sql="select*from employee";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery(sql);
            emp_table.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
         
        JOptionPane.showMessageDialog(null,e);
        
        }
    
    
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        empid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Employee List");
        setMinimumSize(new java.awt.Dimension(1372, 772));
        setResizable(false);
        getContentPane().setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(102, 102, 102));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton14.setBackground(new java.awt.Color(51, 0, 0));
        jButton14.setForeground(new java.awt.Color(51, 0, 51));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusable(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton14);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_blue.png"))); // NOI18N
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setOpaque(false);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton16);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(10, 190, 480, 70);

        jLabel12.setBackground(new java.awt.Color(0, 0, 102));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("B I S C U I T  M A N U F A C T U R E R S");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 100, 270, 40);

        jLabel21.setBackground(new java.awt.Color(0, 0, 102));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("           L U C K Y L A N D");
        jLabel21.setOpaque(true);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(60, 40, 300, 60);

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 20, 480, 160);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 320, 160, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mobile");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 380, 120, 23);

        mob.setBackground(new java.awt.Color(204, 204, 255));
        mob.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        mob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(mob);
        mob.setBounds(260, 380, 220, 40);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 450, 120, 23);

        uname.setBackground(new java.awt.Color(204, 204, 255));
        uname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        uname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname);
        uname.setBounds(260, 440, 220, 40);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 510, 120, 23);

        password.setBackground(new java.awt.Color(204, 204, 255));
        password.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(260, 500, 220, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 570, 120, 23);

        email.setBackground(new java.awt.Color(204, 204, 255));
        email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(email);
        email.setBounds(260, 560, 220, 40);

        delete.setBackground(new java.awt.Color(153, 153, 153));
        delete.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rem.png"))); // NOI18N
        delete.setText("DELETE");
        delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(380, 640, 100, 50);

        update.setBackground(new java.awt.Color(153, 153, 153));
        update.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h.png"))); // NOI18N
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(260, 640, 100, 50);

        empid.setBackground(new java.awt.Color(204, 204, 255));
        empid.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        empid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        empid.setOpaque(true);
        getContentPane().add(empid);
        empid.setBounds(260, 320, 220, 40);

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 290, 480, 430);

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 500, 790);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("                       View Employee List");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(730, 20, 390, 30);

        emp_table.setBackground(new java.awt.Color(204, 255, 204));
        emp_table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emp_table.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        emp_table.setSelectionBackground(new java.awt.Color(0, 0, 102));
        emp_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emp_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(520, 140, 830, 470);

        jLabel8.setBackground(new java.awt.Color(0, 153, 153));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("            Enter the Employee Name or ID to be searched");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(790, 80, 560, 40);

        search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(570, 80, 220, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search (1).png"))); // NOI18N
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 80, 50, 40);

        count.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        count.setOpaque(true);
        getContentPane().add(count);
        count.setBounds(790, 640, 130, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TOTAL NUMBER OF EMPLOYEES");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 640, 230, 40);

        jButton2.setBackground(new java.awt.Color(255, 51, 255));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.png"))); // NOI18N
        jButton2.setText("Generate Report");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1100, 640, 220, 40);

        jLabel14.setBackground(new java.awt.Color(0, 153, 153));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 630, 830, 60);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 40, 850, 680);

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 1440, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        MainHomeUI mh=new MainHomeUI();
        mh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        AdminmenuUI mh=new AdminmenuUI();
        mh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void emp_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_tableMouseClicked

        try{
            int row=emp_table.getSelectedRow();
            String Table_click=(emp_table.getModel().getValueAt(row, 0).toString());
        
            String sql="select*from employee where empid='"+Table_click+"'";
            
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                
            String add1=rs.getString("empid");
            empid.setText(add1);
            String add2=rs.getString("mobile");
            mob.setText(add2);
            String add3=rs.getString("uname");
            uname.setText(add3);
            String add4=rs.getString("password");
            password.setText(add4);             
            String add5=rs.getString("email");
            
            email.setText(add5);
            }
        }
        catch(Exception e){
        
                        JOptionPane.showMessageDialog(null,e);

        
        }
    }//GEN-LAST:event_emp_tableMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
           
        String val1=empid.getText();
            
            if(val1.isEmpty())
            {
                        JOptionPane.showMessageDialog(null,"Employee ID should be Numeric It can not be Empty!");

            }
            
       else
            {
                
        int p=JOptionPane.showConfirmDialog(null,"Do you really want to Delete the Data?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        
        String sql="delete from employee where empid=?";
        
        try{
        
        
        pst=con.prepareStatement(sql);
        pst.setString(1,empid.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null,"Record Deleted Successfully!");
 
        }
        
        catch(Exception e){
            
        JOptionPane.showMessageDialog(null,e);
        
        }
        
        update_table();
    }//GEN-LAST:event_deleteActionPerformed
   }
  }
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

//        String vemail=email.getText();
//        String vmob=mob.getText();
//        String vuname=uname.getText();
//       
//        String vpassword=password.getText();
        
      
            String val1=empid.getText();
            String val2=mob.getText();
            String val3=uname.getText();
            String val4=password.getText();
            String val5=email.getText();
       
      
       
       //Strating Validations.....
       
        String emailPat="^[a-zA-Z0-9]{1,20}@[a-zA-Z0-9]{1,20}.[a-zA-Z]{2,3}$";   
        Pattern pat=Pattern.compile(emailPat);
        Matcher regexMatcher=pat.matcher(val5);
       
         String passpat="((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20})";
         Pattern pat3=Pattern.compile(passpat);
         Matcher regexMatcher3=pat3.matcher(password.getText());
         
         String mobpat="^[0-9]{10}$";
         Pattern pat4=Pattern.compile(mobpat);
         Matcher regexMatcher4=pat4.matcher(val2);


         //String val1=empid.getText();
            
          if(val1.isEmpty())
          {
               JOptionPane.showMessageDialog(null,"Employee ID should be Numeric It can not be Empty!");


              
            }
         
         else if(!regexMatcher.matches()){
        
        JOptionPane.showMessageDialog(null,"Invalid E-mail Format!");
            
            
        }
         
         
         else if(!regexMatcher4.matches())
         {
           JOptionPane.showMessageDialog(null,"Invalid Mobile Number Format!");

         
         }
         
         
         else if(!regexMatcher3.matches()){
    
             JOptionPane.showMessageDialog(null,"Invalid Password Format.Include atleast 6 charactors with Upper case,Special charactor and a Number! ");

    
            }
         
         
         else {
             
             
        
        try
        {
//            String val1=empid.getText();
//            String val2=mob.getText();
//            String val3=uname.getText();
//            String val4=password.getText();
//            String val5=email.getText();
            
            

            String sql="update employee set mobile='"+val2+"',uname='"+val3+"',password='"+val4+"',email='"+val5+"' where empid='"+val1+"'";
            pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Record Updated Successfully!");
            
            
            

        }
         
        catch(Exception e)
        {
            
                JOptionPane.showMessageDialog(null,e);

        }
        
                update_table();

    }//GEN-LAST:event_updateActionPerformed

    }
    
    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased

        try
        {
        String sql="select* from employee where empName=?";
        
        pst=con.prepareStatement(sql);
        pst.setString(1, search.getText());
        
        rs=pst.executeQuery();
        if(rs.next())
        {
        String ad1=rs.getString("empId");
        empid.setText(ad1);
        
         String ad2=rs.getString("mobile");
        mob.setText(ad2);
        
         String ad3=rs.getString("uname");
        uname.setText(ad3);
        
         String ad4=rs.getString("password");
        password.setText(ad4);
        
         String ad5=rs.getString("email");
        email.setText(ad5);
        
        }
            
        }
        
        catch(Exception e)
        
        {
                            JOptionPane.showMessageDialog(null,e);

        }

         
        
         try
        {
        String sql="select* from employee where uname=?";
        
        pst=con.prepareStatement(sql);
        pst.setString(1, search.getText());
        
        rs=pst.executeQuery();
        if(rs.next())
        {
        String ad1=rs.getString("empId");
        empid.setText(ad1);
        
         String ad2=rs.getString("mobile");
        mob.setText(ad2);
        
         String ad3=rs.getString("uname");
        uname.setText(ad3);
        
         String ad4=rs.getString("password");
        password.setText(ad4);
        
         String ad5=rs.getString("email");
        email.setText(ad5);
        
        }
            
        }
        
        catch(Exception e)
        
        {
                            JOptionPane.showMessageDialog(null,e);

        }
         
         
         
          try
        {
        String sql="select* from employee where empId=?";
        
        pst=con.prepareStatement(sql);
        pst.setString(1, search.getText());
        
        rs=pst.executeQuery();
        if(rs.next())
        {
        String ad1=rs.getString("empId");
        empid.setText(ad1);
        
         String ad2=rs.getString("mobile");
        mob.setText(ad2);
        
         String ad3=rs.getString("uname");
        uname.setText(ad3);
        
         String ad4=rs.getString("password");
        password.setText(ad4);
        
         String ad5=rs.getString("email");
        email.setText(ad5);
        
        }
            
        }
        
        catch(Exception e)
        
        {
                            JOptionPane.showMessageDialog(null,e);

        }


    }//GEN-LAST:event_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            try{
                String sql="select count(empId)from employee";
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                
                String counting=rs.getString("count(empId)");
                count.setText(counting);
                
                
                }
                
            }
            catch(Exception e){
            
                
                 JOptionPane.showMessageDialog(null,e);

                
            }



                update_table();



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//        try
//        {
//        String report="C:\\Users\\Nilfa.RS\\JaspersoftWorkspace\\MyReports\\ReportEmployeeInfo.jrxml";
//        JasperReport jr=JasperCompileManager.compileReport(report);
//        JasperPrint jp=JasperFillManager.fillReport(jr,null,con);
//        JasperViewer.viewReport(jp);
//        
//        
//        
//        }
//        
//        catch(Exception e)
//        {
//        
//               JOptionPane.showMessageDialog(null,e);
//
//            
//        }

  try {
            DBConnection db = new DBConnection();
            Connection con = db.connect();
            
            InputStream in = new FileInputStream(new File("C:\\Users\\Nilfa.RS\\Desktop\\TEchNinjas_project\\TEchNinjas_project\\Project_distributers\\Project_distributers\\src\\jasper\\ReportEmployeeInfo.jrxml"));
            JasperDesign jd = JRXmlLoader.load(in);
            String sql = "select * from employee";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            HashMap para = new HashMap();
            JasperPrint j = JasperFillManager.fillReport(jr, para,con);
            JasperViewer.viewReport(j,false);
            //OutputStream os = new FileOutputStream(new File("E:\\Report"));
            //JasperExportManager.exportReportToPdfStream(j,os);
        } catch (Exception e) {
        
            e.printStackTrace();
        }
        




    }//GEN-LAST:event_jButton2ActionPerformed

        
      
        
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        

        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewEmployee().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel count;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTable emp_table;
    private javax.swing.JLabel empid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField mob;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField search;
    private javax.swing.JTextField uname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
